### ISSUE TITLE
DataTables sometimes gets set up with no headers

### ISSUE THREAD

**Issue by kortemik** [teragrep/ajs_01#158]
ID <243>
Reporter <@StrongestNumber9>

It will cause issues and popups like

```sh
DataTables warning: table id=DT_table_paragraph_1661239442143_1589163760 - Requested unknown parameter '9' for row 0, column 9. For more information about this error, please see http://datatables.net/tn/4
```

and from console logs

```sh
ERROR [2022-08-23 13:46:02,702] ({qtp1470344997-1398} NotebookServer.java[onMessage]:461) - Can't handle message: {"op":"ANGULAR_OBJECT_UPDATED","data":{"noteId":"2HB82YR69","paragraphId":"paragraph_1661239998297_68801971","name":"AJAXRequest","value":"{\"draw\":1,\"columns\":[{\"data\":0,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}},{\"data\":1,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}},{\"data\":2,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}},{\"data\":3,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}},{\"data\":4,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}},{\"data\":5,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}},{\"data\":6,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}},{\"data\":7,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}},{\"data\":8,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}},{\"data\":9,\"name\":\"\",\"searchable\":true,\"orderable\":true,\"search\":{\"value\":\"\",\"regex\":false}}],\"order\":[{\"column\":0,\"dir\":\"desc\"},{\"column\":0,\"dir\":\"asc\"}],\"start\":0,\"length\":25,\"search\":{\"value\":\"\",\"regex\":false}}","interpreterGroupId":"spark-q000015a-2HB82YR69"},"principal":"q000009a","ticket":"3bf566fb-bfc6-4ecf-a0f7-d6631a986201","roles":"[\"sysadmins\"]","msgId":"cssv9-11"}
java.lang.NullPointerException
        at org.apache.zeppelin.socket.NotebookServer$31.onSuccess(NotebookServer.java:1357)
        at org.apache.zeppelin.socket.NotebookServer$31.onSuccess(NotebookServer.java:1350)
```

This behaviour was met when dealing with error cases on dpl parser so it might not be a problem if dpl doesn't cause one.

Related tickets 
pth_10 #255
pth_10 #256

**Comment by sryhanen** [comment]
Fixed datatables implementations with #325 and #361.
